### PR TITLE
Update man page

### PR DESCRIPTION
**Pull request by thrasibule**

### CODE REVIEW

**Comment by miekg** [comment]
Thanks for you PR! But what does this fix? IIIRC the -simple manpage didn't need any processing, hence it was in autoconf list?

**Comment by thrasibule** [comment]
Putting it in the autoconf list is just so that the version gets updated automatically (it shows 1.1.14 right now).
Other than that, I was reading the man page to try and understand how rdup-simple works, but it was referring to tools that are no longer in the distribution (rdup-snapshot, rdup-snap-link) and the options didn't match, so it was really confusing. This brings it up to the current state of the script I think, and fix some formatting issues.

**Comment by miekg** [comment]
Note that I have no time left to work on rdup anymore and most of coding is in Go nowadays anyway. I can give you push access to this repo?

**Comment by thrasibule** [comment]
Thanks, appreciate it but I don't feel confident I could make some changes to the code. I'm happy just being a user :)

**Pull request merged**
